import {
  createBranch,
  createPullRequest,
  getDefaultBranchSha,
  getFileContent,
  upsertFile,
} from "@/lib/integrations/github-write-client";
import type { CodingJob, CodingJobChangedFile } from "@/lib/types/coding-job";
import type { CodingJobLog } from "@/lib/types/coding-job-log";

function log(
  logs: CodingJobLog[],
  level: CodingJobLog["level"],
  message: string,
  phase?: string,
): CodingJobLog[] {
  return [
    ...logs,
    {
      id: `log-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      timestamp: new Date().toISOString(),
      level,
      message,
      phase,
    },
  ];
}

function appJobUrl(jobId: string): string | undefined {
  const base = process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/$/, "");
  if (!base) return undefined;
  return `${base}/coding?detail=${jobId}`;
}

function listSection(title: string, items: string[] | undefined): string {
  if (!items?.length) return `## ${title}\n\n_None listed_\n`;
  return `## ${title}\n\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function buildJobDoc(job: CodingJob): string {
  const plan = job.plan;
  const steps = plan?.steps
    .map(
      (s) =>
        `- [ ] **${s.order}. ${s.title}**${s.description ? ` — ${s.description}` : ""}`,
    )
    .join("\n");
  const appLink = appJobUrl(job.id);

  return `# Octane coding job ${job.id}

**Repo:** \`${job.repo}\`  
**Mode:** ${job.mode} — Review mode creates a branch + planning PR only. Never auto-merge or deploy.  
**Project:** ${job.projectId ?? "—"}  
**Status:** ${job.status}

## Understood request

${plan?.understoodRequest ?? job.prompt}

## Plan summary

${plan?.summary ?? "_No plan_"}

## Steps

${steps ?? "_No steps_"}

${listSection("Files likely to touch", plan?.files)}

${listSection("Risks", plan?.risks)}

${listSection("Test / build checklist", plan?.testPlan)}

${listSection("Review items", plan?.reviewItems)}

${listSection("What will NOT happen automatically", plan?.wontAutoHappen)}

## Prompt (original)

${job.prompt}

## Next steps

1. Review this PR in GitHub — planning doc only in v1 (no source edits).
2. Approve or request changes in Octane before any follow-up implementation PRs.
3. Run local tests before merging on GitHub.
4. Octane never merges, deploys, or changes repo settings.

${appLink ? `\n[Open in Octane](${appLink})\n` : ""}
`;
}

function buildPrBody(job: CodingJob): string {
  const appLink = appJobUrl(job.id);
  return `## Octane planning pull request

This PR was opened by **Octane Coding Workbench** in **review mode**. It contains a planning document only — **no application source edits in v1**.

| | |
|---|---|
| **Job ID** | \`${job.id}\` |
| **Mode** | ${job.mode} |
| **Repo** | \`${job.repo}\` |

### Plan summary

${job.plan?.summary ?? "_See job doc in this PR_"}

### What happens next

1. Review \`docs/octane-coding-jobs/${job.id}.md\` in this PR.
2. Approve the job in Octane if the plan looks right.
3. Future checkpoints may add implementation commits — still **no auto-merge** from Octane.

### What Octane will NOT do

${(job.plan?.wontAutoHappen ?? ["Auto-merge", "Deploy", "Delete branches/repos"]).map((w) => `- ${w}`).join("\n")}

${appLink ? `\n[Review in Octane](${appLink})\n` : ""}

---
_Generated by Octane — branch + PR only. Merge and deploy remain manual on GitHub/Vercel._
`;
}

export type RunCodingJobResult = {
  status: CodingJob["status"];
  logs: CodingJobLog[];
  changedFiles: CodingJobChangedFile[];
  branchName?: string;
  baseBranch?: string;
  prNumber?: number;
  prUrl?: string;
  errorMessage?: string;
};

/**
 * Safe first implementation: branch + docs file + PR (never merge).
 */
export async function runCodingJobOnGitHub(job: CodingJob): Promise<RunCodingJobResult> {
  let logs = job.logs;
  const changedFiles: CodingJobChangedFile[] = [...job.changedFiles];

  logs = log(logs, "info", "Starting GitHub workflow (branch → file → PR)", "run");

  const base = await getDefaultBranchSha(job.repo);
  if (!base.ok) {
    logs = log(logs, "error", base.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      errorMessage: base.error,
    };
  }

  logs = log(logs, "info", `Base branch: ${base.data.branch} (${base.data.sha.slice(0, 7)})`, "run");

  const branchName =
    job.branchName ?? `octane/coding-${job.id.replace(/[^a-zA-Z0-9-]/g, "").slice(0, 24)}`;

  const branchResult = await createBranch(job.repo, branchName, base.data.sha);
  if (!branchResult.ok) {
    if (branchResult.status === 422) {
      logs = log(logs, "warn", `Branch ${branchName} may already exist — continuing`, "run");
    } else {
      logs = log(logs, "error", branchResult.error, "run");
      return {
        status: "failed",
        logs,
        changedFiles,
        branchName,
        baseBranch: base.data.branch,
        errorMessage: branchResult.error,
      };
    }
  } else {
    logs = log(logs, "success", `Created branch ${branchName}`, "run");
  }

  const docPath = `docs/octane-coding-jobs/${job.id}.md`;
  const existing = await getFileContent(job.repo, docPath, branchName);
  if (!existing.ok) {
    logs = log(logs, "error", existing.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: existing.error,
    };
  }

  const docContent = buildJobDoc({ ...job, branchName, baseBranch: base.data.branch });
  const upsert = await upsertFile(
    job.repo,
    docPath,
    branchName,
    docContent,
    `chore(octane): add coding job plan ${job.id}`,
    existing.data?.sha,
  );

  if (!upsert.ok) {
    logs = log(logs, "error", upsert.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: upsert.error,
    };
  }

  changedFiles.push({
    path: docPath,
    action: existing.data ? "modify" : "add",
  });
  logs = log(logs, "success", `Upserted ${docPath}`, "run");

  const prTitle = `Octane plan: ${job.title}`;
  const prBody = buildPrBody(job);

  const pr = await createPullRequest(
    job.repo,
    prTitle,
    branchName,
    base.data.branch,
    prBody,
  );

  if (!pr.ok) {
    logs = log(logs, "error", pr.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: pr.error,
    };
  }

  logs = log(
    logs,
    "success",
    `Opened PR #${pr.data.number}: ${pr.data.html_url}`,
    "run",
  );

  return {
    status: "pr_open",
    logs,
    changedFiles,
    branchName,
    baseBranch: base.data.branch,
    prNumber: pr.data.number,
    prUrl: pr.data.html_url,
  };
}
