import {
  createBranch,
  createPullRequest,
  getDefaultBranchSha,
  getFileContent,
  upsertFile,
} from "@/lib/integrations/github-write-client";
import type { CodingJob, CodingJobChangedFile } from "@/lib/types/coding-job";
import type { CodingJobLog } from "@/lib/types/coding-job-log";

function log(
  logs: CodingJobLog[],
  level: CodingJobLog["level"],
  message: string,
  phase?: string,
): CodingJobLog[] {
  return [
    ...logs,
    {
      id: `log-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      timestamp: new Date().toISOString(),
      level,
      message,
      phase,
    },
  ];
}

function buildJobDoc(job: CodingJob): string {
  const plan = job.plan;
  const steps = plan?.steps
    .map((s) => `- [ ] **${s.order}. ${s.title}**${s.description ? ` — ${s.description}` : ""}`)
    .join("\n");
  return `# Octane coding job ${job.id}

**Repo:** \`${job.repo}\`  
**Mode:** ${job.mode} (review-first — no auto-merge)  
**Project:** ${job.projectId ?? "—"}  
**Status:** ${job.status}

## Prompt

${job.prompt}

## Plan summary

${plan?.summary ?? "_No plan_"}

## Steps

${steps ?? "_No steps_"}

## Files to touch

${(plan?.files ?? []).map((f) => `- \`${f}\``).join("\n") || "_None listed_"}

## Risks

${(plan?.risks ?? []).map((r) => `- ${r}`).join("\n") || "_None_"}

## Test plan

${(plan?.testPlan ?? []).map((t) => `- ${t}`).join("\n") || "_None_"}

## Next steps

1. Review this PR in GitHub.
2. Approve or request changes — Octane never merges automatically.
3. Run local tests before merging.
`;
}

export type RunCodingJobResult = {
  status: CodingJob["status"];
  logs: CodingJobLog[];
  changedFiles: CodingJobChangedFile[];
  branchName?: string;
  baseBranch?: string;
  prNumber?: number;
  prUrl?: string;
  errorMessage?: string;
};

/**
 * Safe first implementation: branch + docs file + PR (never merge).
 */
export async function runCodingJobOnGitHub(job: CodingJob): Promise<RunCodingJobResult> {
  let logs = job.logs;
  const changedFiles: CodingJobChangedFile[] = [...job.changedFiles];

  logs = log(logs, "info", "Starting GitHub workflow (branch → file → PR)", "run");

  const base = await getDefaultBranchSha(job.repo);
  if (!base.ok) {
    logs = log(logs, "error", base.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      errorMessage: base.error,
    };
  }

  logs = log(logs, "info", `Base branch: ${base.data.branch} (${base.data.sha.slice(0, 7)})`, "run");

  const branchName =
    job.branchName ?? `octane/coding-${job.id.replace(/[^a-zA-Z0-9-]/g, "").slice(0, 24)}`;

  const branchResult = await createBranch(job.repo, branchName, base.data.sha);
  if (!branchResult.ok) {
    if (branchResult.status === 422) {
      logs = log(logs, "warn", `Branch ${branchName} may already exist — continuing`, "run");
    } else {
      logs = log(logs, "error", branchResult.error, "run");
      return {
        status: "failed",
        logs,
        changedFiles,
        branchName,
        baseBranch: base.data.branch,
        errorMessage: branchResult.error,
      };
    }
  } else {
    logs = log(logs, "success", `Created branch ${branchName}`, "run");
  }

  const docPath = `docs/octane-coding-jobs/${job.id}.md`;
  const existing = await getFileContent(job.repo, docPath, branchName);
  if (!existing.ok) {
    logs = log(logs, "error", existing.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: existing.error,
    };
  }

  const docContent = buildJobDoc({ ...job, branchName, baseBranch: base.data.branch });
  const upsert = await upsertFile(
    job.repo,
    docPath,
    branchName,
    docContent,
    `chore(octane): add coding job doc ${job.id}`,
    existing.data?.sha,
  );

  if (!upsert.ok) {
    logs = log(logs, "error", upsert.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: upsert.error,
    };
  }

  changedFiles.push({
    path: docPath,
    action: existing.data ? "modify" : "add",
  });
  logs = log(logs, "success", `Upserted ${docPath}`, "run");

  const prTitle = `[Octane] ${job.title}`;
  const prBody = `## Octane coding job

**Job ID:** \`${job.id}\`  
**Mode:** ${job.mode}  
**Prompt:** ${job.prompt.slice(0, 500)}

This PR was opened by Octane Coding Workbench. **Do not auto-merge** — review the plan doc and apply follow-up commits as needed.

### Plan

${job.plan?.summary ?? "_See job doc_"}

---
_Generated by Octane — no merge or deploy actions performed._`;

  const pr = await createPullRequest(
    job.repo,
    prTitle,
    branchName,
    base.data.branch,
    prBody,
  );

  if (!pr.ok) {
    logs = log(logs, "error", pr.error, "run");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      errorMessage: pr.error,
    };
  }

  logs = log(
    logs,
    "success",
    `Opened PR #${pr.data.number}: ${pr.data.html_url}`,
    "run",
  );

  return {
    status: "pr_open",
    logs,
    changedFiles,
    branchName,
    baseBranch: base.data.branch,
    prNumber: pr.data.number,
    prUrl: pr.data.html_url,
  };
}
