import {
  createBranch,
  createPullRequest,
  getDefaultBranchSha,
  getFileContent,
  upsertFile,
} from "@/lib/integrations/github-write-client";
import type {
  CodingJob,
  CodingJobChangedFile,
  CodingJobProposedEdit,
} from "@/lib/types/coding-job";
import type { CodingJobLog } from "@/lib/types/coding-job-log";

import {
  assertFeatureBranch,
  validateProposedEditsForApply,
} from "./edit-guardrails";

function log(
  logs: CodingJobLog[],
  level: CodingJobLog["level"],
  message: string,
  phase?: string,
): CodingJobLog[] {
  return [
    ...logs,
    {
      id: `log-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      timestamp: new Date().toISOString(),
      level,
      message,
      phase,
    },
  ];
}

function appJobUrl(jobId: string): string | undefined {
  const base = process.env.NEXT_PUBLIC_APP_URL?.trim().replace(/\/$/, "");
  if (!base) return undefined;
  return `${base}/coding?detail=${jobId}`;
}

function buildSourcePrBody(job: CodingJob, edits: CodingJobProposedEdit[]): string {
  const appLink = appJobUrl(job.id);
  const fileList = edits
    .map((e) => `- \`${e.path}\` — ${e.summary}`)
    .join("\n");

  return `## Octane source pull request

This PR contains **reviewed source edits** proposed in Octane Coding Workbench. Octane does **not** auto-merge or deploy.

| | |
|---|---|
| **Job ID** | \`${job.id}\` |
| **Mode** | ${job.mode} |
| **Repo** | \`${job.repo}\` |

### Files changed

${fileList}

### Plan summary

${job.plan?.summary ?? "_See job doc in this PR_"}

### Review checklist

${(job.plan?.reviewItems ?? ["Run npm run build", "Smoke-test affected UI", "Review diff on GitHub"]).map((i) => `- ${i}`).join("\n")}

### What Octane will NOT do

${(job.plan?.wontAutoHappen ?? ["Auto-merge", "Deploy", "Delete branches/repos"]).map((w) => `- ${w}`).join("\n")}

${appLink ? `\n[Review in Octane](${appLink})\n` : ""}

---
_Generated by Octane — branch + PR only. Merge and deploy remain manual._
`;
}

function buildSourceJobDoc(job: CodingJob, edits: CodingJobProposedEdit[]): string {
  const appLink = appJobUrl(job.id);
  const editLines = edits
    .map((e) => `- **${e.path}** — ${e.summary}`)
    .join("\n");

  return `# Octane source coding job ${job.id}

**Repo:** \`${job.repo}\`  
**PR kind:** source (implementation)  
**Status:** ${job.status}

## Request

${job.prompt}

## Applied edits

${editLines}

## Safety

- No auto-merge or deploy from Octane.
- Edits were approved in Octane before this PR was opened.

${appLink ? `\n[Open in Octane](${appLink})\n` : ""}
`;
}

export type RunSourceCodingJobResult = {
  status: CodingJob["status"];
  logs: CodingJobLog[];
  changedFiles: CodingJobChangedFile[];
  branchName?: string;
  baseBranch?: string;
  prNumber?: number;
  prUrl?: string;
  prKind: "source";
  errorMessage?: string;
};

export async function runSourceCodingJobOnGitHub(
  job: CodingJob,
): Promise<RunSourceCodingJobResult> {
  const edits = job.proposedEdits ?? [];
  const guard = validateProposedEditsForApply(job, edits);
  if (!guard.ok) {
    return {
      status: "failed",
      logs: log(job.logs, "error", guard.error, "source-pr"),
      changedFiles: [...job.changedFiles],
      prKind: "source",
      errorMessage: guard.error,
    };
  }

  let logs = job.logs;
  const changedFiles: CodingJobChangedFile[] = [...job.changedFiles];

  logs = log(logs, "info", "Starting source PR workflow", "source-pr");

  const base = await getDefaultBranchSha(job.repo);
  if (!base.ok) {
    logs = log(logs, "error", base.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      prKind: "source",
      errorMessage: base.error,
    };
  }

  const branchName =
    job.branchName ??
    `octane/source-${job.id.replace(/[^a-zA-Z0-9-]/g, "").slice(0, 20)}`;

  const branchGuard = assertFeatureBranch(branchName);
  if (!branchGuard.ok) {
    logs = log(logs, "error", branchGuard.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      prKind: "source",
      errorMessage: branchGuard.error,
    };
  }

  const branchResult = await createBranch(job.repo, branchName, base.data.sha);
  if (!branchResult.ok && branchResult.status !== 422) {
    logs = log(logs, "error", branchResult.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      prKind: "source",
      errorMessage: branchResult.error,
    };
  }
  logs = log(logs, "success", `Using branch ${branchName}`, "source-pr");

  for (const edit of edits) {
    const existing = await getFileContent(job.repo, edit.path, branchName);
    if (!existing.ok) {
      logs = log(logs, "error", existing.error, "source-pr");
      return {
        status: "failed",
        logs,
        changedFiles,
        branchName,
        baseBranch: base.data.branch,
        prKind: "source",
        errorMessage: existing.error,
      };
    }

    const upsert = await upsertFile(
      job.repo,
      edit.path,
      branchName,
      edit.afterContent,
      `feat(octane): ${edit.summary.slice(0, 72)}`,
      existing.data?.sha,
    );

    if (!upsert.ok) {
      logs = log(logs, "error", upsert.error, "source-pr");
      return {
        status: "failed",
        logs,
        changedFiles,
        branchName,
        baseBranch: base.data.branch,
        prKind: "source",
        errorMessage: upsert.error,
      };
    }

    changedFiles.push({
      path: edit.path,
      action: existing.data ? "modify" : "add",
    });
    logs = log(logs, "success", `Applied ${edit.path}`, "source-pr");
  }

  const docPath = `docs/octane-coding-jobs/${job.id}-source.md`;
  const docExisting = await getFileContent(job.repo, docPath, branchName);
  if (!docExisting.ok) {
    logs = log(logs, "error", docExisting.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      prKind: "source",
      errorMessage: docExisting.error,
    };
  }

  const docContent = buildSourceJobDoc(
    { ...job, branchName, baseBranch: base.data.branch },
    edits,
  );
  const docUpsert = await upsertFile(
    job.repo,
    docPath,
    branchName,
    docContent,
    `chore(octane): source job summary ${job.id}`,
    docExisting.data?.sha,
  );
  if (!docUpsert.ok) {
    logs = log(logs, "error", docUpsert.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      prKind: "source",
      errorMessage: docUpsert.error,
    };
  }
  changedFiles.push({
    path: docPath,
    action: docExisting.data ? "modify" : "add",
  });

  const prTitle = `Octane: ${job.title}`;
  const prBody = buildSourcePrBody(job, edits);
  const pr = await createPullRequest(
    job.repo,
    prTitle,
    branchName,
    base.data.branch,
    prBody,
  );

  if (!pr.ok) {
    logs = log(logs, "error", pr.error, "source-pr");
    return {
      status: "failed",
      logs,
      changedFiles,
      branchName,
      baseBranch: base.data.branch,
      prKind: "source",
      errorMessage: pr.error,
    };
  }

  logs = log(
    logs,
    "success",
    `Opened source PR #${pr.data.number}: ${pr.data.html_url}`,
    "source-pr",
  );

  return {
    status: "pr_open",
    logs,
    changedFiles,
    branchName,
    baseBranch: base.data.branch,
    prNumber: pr.data.number,
    prUrl: pr.data.html_url,
    prKind: "source",
  };
}
